- docs/index.html
This pull request simply adds user documentation to the `docs/index.html` file.
> Add documentation to docs/index.html file

- RELEASES.md
Add documentation of release 0.1.0
> Update RELEASES.md info for release 0.1.0

- README.md
> Badge for Python 3.6 in README.md file

- conda.recipe/install_local_package.sh
> Fix conda.recipe/install_local_package.sh

- behresp/behavior.py
- behresp/tbi.py
Cosmetic style changes in the code.
> Revise code to eliminate warnings generated by pylint 2.1.1

- conda.recipe/remove_local_package.sh
Minor change to avoid potential package name conflicts.
> Make conda.recipe/remove_local_package.sh safer

- RELEASES.md
- docs/index.html
> Update RELEASES.md info for release 0.4.0

- RELEASES.md
> Fix links in RELEASES.md file

- PSL_catalog.json
This pull request adds a `PSL_catalog.json` file that is required before a project can be considered for inclusion in the Policy Simulation Library.
> Add PSL_catalog.json file

- PSL_catalog.json
Edits recommended by @Peter-Metz in [PSL issue 69](https://github.com/open-source-economics/PSL/issues/69).
> Edit PSL_catalog.json file

- .travis.yml
> Remove .travis.yml 'sudo: false' setting

- README.md
> Add PSL-cataloged badge to README.md file

- README.md
> Change location and color of badges

- .travis.yml
- setup.py
Changes only to configuration files; no logic changes.
> Add Travis-CI tests under Python 3.7

- RELEASES.md
> Update RELEASES.md with information about release 0.4.1

- README.md
- RELEASES.md
> Add documentation for release 0.5.0

- behresp/behavior.py
- behresp/tests/test_behavior.py
This pull request removes the logic added in pull request #37 and postpones the resolution of issue #36 until after the 0.6.0 release.
> Postpone resolution of issue 36

- conda.recipe/install_local_package.sh
- conda.recipe/remove_local_package.sh
This pull request mostly adds documentation to help clarify the process of creating a local `behresp` package.
> Update conda.recipe/*_local_package.sh files

- conda.recipe/install_local_package.sh
> Revisions to conda.recipe/install_local_package.sh script

- RELEASES.md
- docs/index.html
> Update RELEASES.md info and release in docs/index.html file

- behresp/tests/test_behavior.py
Minor changes in expected test results give changes in the calculation of qualified business income deduction introduced in [Tax-Calculator pull request 2345](https://github.com/PSLmodels/Tax-Calculator/pull/2345).
> Update expected test results for changes in calculation of qualified business income deduction

- behresp/tests/test_behavior.py
Minor changes in test results when using Tax-Calculator release 2.4.2.
> Update expected test results for changes in Tax-Calculator 2.4.2

- RELEASES.md
Add release notes for 0.11.0. 
The release will resolve #73. 
cc @jdebacker
> Release 0.11.0
